Add 2.10.0-rc1 version
Added two new args:

   - LUAJIT_DISABLE_SYSPROF to disable sysprof due to an error
     'undefined reference to backtrace' during the build
   - LUAJIT_ENABLE_GC64 to build Tarantool with enabled GC64

Part of tarantool/infra#88